routes/web.php
<?php

use App\Http\Controllers\PagesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::localizedGroup(function () {
    Route::transGet('/', [PagesController::class, 'getHome']);
    Route::transGet('routes.home', [PagesController::class, 'getHome']);
    Route::transGet('routes.our-vehicles', [PagesController::class, 'getOurVehicles']);
    Route::transGet('routes.our-vehicles/car', [PagesController::class, 'getVehicle']);       
    Route::transGet('routes.who-we-are', [PagesController::class, 'getWhoWeAre']);
    Route::transGet('routes.buying-and-selling', [PagesController::class, 'getBuyingAndSelling']);
    Route::transPost('routes.buying-and-selling', [PagesController::class, 'postBuyingAndSelling']);
    Route::transGet('routes.contact', [PagesController::class, 'getContact']);
    Route::transPost('routes.contact', [PagesController::class, 'postContact']);
    Route::transGet('routes.gallery', [PagesController::class, 'getGallery']);
});

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Spatie\Image\Manipulations;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Car extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    public static function boot() {
        parent::boot();

        static::creating(function ($model) {        
            $slug_nl = Str::slug(str_replace('/', '-', $model->title_nl), '-');
            $slugCount_nl = count(Car::whereRaw("slug_nl REGEXP '^{$slug_nl}(-[0-9]*)?$'")->get() );
            $model->slug_nl = ($slugCount_nl > 0) ? "{$slug_nl}-{$slugCount_nl}" : $slug_nl;

            $slug_fr = Str::slug(str_replace('/', '-', $model->title_fr), '-');
            $slugCount_fr = count(Car::whereRaw("slug_fr REGEXP '^{$slug_fr}(-[0-9]*)?$'")->get() );
            $model->slug_fr = ($slugCount_fr > 0) ? "{$slug_fr}-{$slugCount_nl}" : $slug_fr;

            $slug_en = Str::slug(str_replace('/', '-', $model->title_en), '-');
            $slugCount_en = count(Car::whereRaw("slug_en REGEXP '^{$slug_en}(-[0-9]*)?$'")->get() );
            $model->slug_en = ($slugCount_en > 0) ? "{$slug_en}-{$slugCount_en}" : $slug_nl;            

        });

        static::updating(function ($model) {        
            if($model->isDirty('title_nl')){
                $slug = Str::slug(str_replace('/', '-', $model->title_nl), '-');
                $slugCount = count(Car::whereRaw("slug_nl REGEXP '^{$slug}(-[0-9]*)?$'")->get() );
                $model->slug_nl = ($slugCount > 0) ? "{$slug}-{$slugCount}" : $slug;
            }

            if($model->isDirty('title_fr')){
                $slug = Str::slug(str_replace('/', '-', $model->title_fr), '-');
                $slugCount = count(Car::whereRaw("slug_fr REGEXP '^{$slug}(-[0-9]*)?$'")->get() );
                $model->slug_fr = ($slugCount > 0) ? "{$slug}-{$slugCount}" : $slug;
            }

            if($model->isDirty('title_en')){
                $slug = Str::slug(str_replace('/', '-', $model->title_en), '-');
                $slugCount = count(Car::whereRaw("slug_en REGEXP '^{$slug}(-[0-9]*)?$'")->get() );
                $model->slug_en = ($slugCount > 0) ? "{$slug}-{$slugCount}" : $slug;
            }
            
        });
    }

    public function registerMediaCollections(): void 
    {
        $this->addMediaConversion('thumb')
              ->width(400)
              ->watermark( public_path('img/watermark_thumb.png') )
              ->watermarkPosition(Manipulations::POSITION_BOTTOM_RIGHT)
              ->watermarkPadding(15)
              ->sharpen(10);

        $this->addMediaConversion('full')
              ->width(1200)
              ->watermark( public_path('img/watermark_full.png') )
              ->watermarkPosition(Manipulations::POSITION_BOTTOM_RIGHT)
              ->watermarkPadding(30)
              ->sharpen(10);
    }

    public function getSlugAttribute()
    {
        return $this['slug_'.localization()->getCurrentLocale()];
    }

    public function getTitleAttribute()
    {
        return $this['title_'.localization()->getCurrentLocale()];
    }

    public function geSubTitleAttribute()
    {
        return $this['subtitle_'.localization()->getCurrentLocale()];
    }

    public function getDescriptionAttribute()
    {
        return $this['description_'.localization()->getCurrentLocale()];
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function color()
    {
        return $this->belongsTo(Color::class);
    }

    public function transmission()
    {
        return $this->belongsTo(Transmission::class);
    }

    public function fuel()
    {
        return $this->belongsTo(Fuel::class);
    }
}

app/Models/Fuel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fuel extends Model
{
    use HasFactory;

    public function getNameAttribute()
    {
        return $this['name_'.session('locale')];
    }
    
    public function cars()
    {
        return $this->hasMany(Car::class);
    }
}

app/Http/Livewire/CarsFilter.php
<?php

namespace App\Http\Livewire;

use App\Models\Car;
use Livewire\Component;
use App\Http\Livewire\DataTable\WithSorting;
use App\Http\Livewire\DataTable\WithCachedRows;

class CarsFilter extends Component
{
    use WithSorting, WithCachedRows;

    public $search;
    public $brand;
    public $fuel;
    public $vatRecoverable;

    protected $queryString = [
        'search' => ['except' => '', 'as' => 's'],
        'brand' => ['except' => '', 'as' => 'b'],
        'fuel' => ['except' => '', 'as' => 'f'],
        'vatRecoverable'  => ['except' => '', 'as' => 'v'],
    ];

    public function updatedFilters()
    {
        //$this->resetPage();
    }

    public function resetFilters()
    {
        $this->reset('search','brand','fuel','vatRecoverable');
    }

    public function getRowsQueryProperty()
    {
        $query = Car::query()
            ->when($this->brand, fn($query, $brandId) => $query->where('brand_id', $brandId))
            ->when($this->fuel, fn($query, $fuelId) => $query->where('fuel_id', $fuelId))
            ->when($this->vatRecoverable, fn($query, $vatRecoverable) => $query->where('is_vat_vehicle', 1))
            ->when($this->search, fn($query, $search) => $query->where('title_nl', 'like', '%'.$search.'%')->orWhere('title_fr', 'like', '%'.$search.'%')->orWhere('title_en', 'like', '%'.$search.'%'));

        return $this->applySorting($query);
    }

    public function getRowsProperty()
    {
        return $this->cache(function () {
            return $this->rowsQuery->get();
        });
    }

    public function render()
    {
        return view('livewire.cars-filter', [
            'cars' => $this->rows,
        ]);
    }
}

app/Http/Livewire/CarsIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Car;
use Livewire\Component;

class CarsIndex extends Component
{
    public function render()
    {
        $cars = Car::where('is_featured', 1);
        return view('livewire.cars-index')->with('cars', $cars);
    }
}

app/Http/Livewire/ContactForm.php
<?php

namespace App\Http\Livewire;

use Mail;
use App\Models\MailLog;
use Livewire\Component;

class ContactForm extends Component
{
    public $firstname;
    public $lastname;
    public $email;
    public $telephone;
    public $subject;
    public $message;

    protected $rules = [
        'firstname' => 'required|min:2|max:255',
        'lastname' => 'required|min:2|max:255',
        'email' => 'required|email',
        'telephone' => 'required|max:255',
        'subject' => 'required|min:2|max:255',
        'message' => 'required|min:2',
    ];

    public function submit() {

        $this->validate();

        $messageText = "";
        $messageText .= "<p><strong>First name: </strong>". $this->firstname ."</p>";
        $messageText .= "<p><strong>Last name: </strong>". $this->lastname ."</p>";
        $messageText .= "<p><strong>E-mail: </strong>". $this->email ."</p>";
        $messageText .= "<p><strong>Phone: </strong>". $this->telephone ."</p>";
        $messageText .= "<br>";
        $messageText .= "<p><strong>Subject: </strong>". $this->subject ."</p>";
        $messageText .= "<p><strong>Message: </strong>". $this->message ."</p>";

        $data = array(
            'firstname'     => $this->firstname,
            'lastname'      => $this->lastname,
            'telephone'     => $this->telephone,
            'email'         => $this->email,
            'messageText'   => $this->message,
            'subject'       => $this->subject,
        );

        // Send Mail
        Mail::to("ben.ectors@mac.com")->send(new \App\Mail\ContactForm($data));
 
         // Save mailLog
        $mailLog = new MailLog();
        $mailLog->mail_type = "Contact";
        $mailLog->mail_to = "info@classic-sportscars.be";
        $mailLog->mail_from = $data['email'];
        $mailLog->mail_subject = $this->subject;
        $mailLog->mail_message = $messageText; 
        $mailLog->save();
        
        session()->flash('status', trans('messages.message-sent') );
    }

    public function render()
    {
        return view('livewire.contact-form');
    }
}

app/Http/Livewire/DataTable/WithCachedRows.php
<?php

namespace App\Http\Livewire\DataTable;

trait WithCachedRows
{
    protected $useCache = false;

    public function useCachedRows()
    {
        $this->useCache = true;
    }

    public function cache($callback)
    {
        $cacheKey = $this->id;

        if ($this->useCache && cache()->has($cacheKey)) {
            return cache()->get($cacheKey);
        }

        $result = $callback();

        cache()->put($cacheKey, $result);

        return $result;
    }
}

app/Http/Livewire/DataTable/WithSorting.php
<?php

namespace App\Http\Livewire\DataTable;

trait WithSorting
{
    public $sorts = [];

    public function sortBy($field)
    {
       if (! isset($this->sorts[$field])) return $this->sorts[$field] = 'asc';

       if ($this->sorts[$field] === 'asc') return $this->sorts[$field] = 'desc';

        unset($this->sorts[$field]);
    }

    public function applySorting($query)
    {
        foreach ($this->sorts as $field => $direction) {
            $query->orderBy($field, $direction);
        }

        return $query;
    }
}

app/Http/Livewire/SellForm.php
<?php

namespace App\Http\Livewire;

use Mail;
use App\Models\MailLog;
use Livewire\Component;
use Livewire\WithFileUploads;

class SellForm extends Component
{
    use WithFileUploads;

    public $firstname;
    public $lastname;
    public $email;
    public $telephone;
    public $brand;
    public $description;
    public $website;
    public $file;

    protected $rules = [
        'firstname' => 'required|min:2|max:255',
        'lastname' => 'required|min:2|max:255',
        'email' => 'required|email',
        'telephone' => 'required|max:255',
        'brand' => 'required|max:255',
        'description' => 'required|min:2',
        'website' => 'nullable|url',
        'file' => 'nullable|mimes:png,jpg,jpeg|max:8096',
    ];

    public function submit() {

        $this->validate();

        $messageText = "";
        $messageText .= "<p><strong>First name: </strong>". $this->firstname ."</p>";
        $messageText .= "<p><strong>Last name: </strong>". $this->lastname ."</p>";
        $messageText .= "<p><strong>E-mail: </strong>". $this->email ."</p>";
        $messageText .= "<p><strong>Phone: </strong>". $this->telephone ."</p>";
        $messageText .= "<br>";
        $messageText .= "<p><strong>Marque: </strong>". $this->brand ."</p>";
        $messageText .= "<p><strong>Déscription: </strong>". $this->description ."</p>";
        $messageText .= "<p><strong>Site web: </strong>". $this->website ."</p>";

        $data = array(
            'firstname' => $this->firstname,
            'lastname' => $this->lastname,
            'email' => $this->email,
            'telephone' => $this->telephone,
            'brand' => $this->brand,
            'description' => $this->description,
            'website' => $this->website,
            'messageText' => $messageText,
            'file' => $this->file
        );   

        // Send Mail
        Mail::to("ben.ectors@mac.com")->send(new \App\Mail\SellForm($data));
    
        // Save mailLog
        $mailLog = new MailLog();
        $mailLog->mail_type = "Reprise";
        $mailLog->mail_to = "info@classic-sportscars.be";
        $mailLog->mail_from = $data['email'];
        $mailLog->mail_subject = "Reprise de véhicule";;
        $mailLog->mail_message = $messageText; 
        $mailLog->save();
        
        session()->flash('status', trans('messages.message-sent') );
    }

    public function render()
    {
        return view('livewire.sell-form');
    }
}

resources/views/livewire/cars-filter.blade.php
<div>

    <div class="bg-gray-50 border border-gray-200 rounded-2xl p-4 mb-8 flex flex-col space-y-2 sm:space-y-0 sm:flex-row sm:justify-between">
        <div class="flex flex-col sm:flex-row sm:items-center space-y-2 sm:space-y-0 sm:space-x-4">

            <input
                type="text"
                wire:model="search"
                placeholder="{{ trans('messages.search-cars',[],session('locale')) }}"
                class="w-full sm:w-56 md:w-64 bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-400 transition duration-200 focus:border-gray-400 transition duration-200"
            />

            <select wire:model="fuel" class="w-auto bg-gray-100 placeholder-gray-300 border border-gray-200 rounded-md py-2 pl-2 pr-10 focus:outline-none focus:ring-gray-400 transition duration-200 focus:border-gray-400 transition duration-200">
                <option value="">{{  trans('messages.select-fuel',[],session('locale')) }}</option>
                @foreach (App\Models\Fuel::all() as $fuel)
                    <option value="{{ $fuel->id }}">{{ $fuel->name }}</option>
                @endforeach
            </select>

            <select wire:model="brand" class="w-auto bg-gray-100 placeholder-gray-300 border border-gray-200 rounded-md py-2 pl-2 pr-10 focus:outline-none focus:ring-gray-400 transition duration-200 focus:border-gray-400 transition duration-200">
                <option value="">{{ trans('messages.select-brand',[],session('locale')) }}</option>
                @foreach (App\Models\Brand::all() as $brand)
                <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                @endforeach
            </select>

            <div class="relative flex items-start">
                <div class="flex h-6 items-center">
                    <input id="vat_recoverable" wire:model="vatRecoverable" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-gray-600 focus:ring-gray-600">
                </div>
                <div class="ml-3">
                    <label for="vat_recoverable" class="text-sm font-medium leading-6 text-gray-900">
                        {{ trans('messages.vat-recoverable',[],session('locale')) }}
                    </label>
                </div>
            </div>




        </div>

        <button type="button" wire:click="resetFilters" class="bg-gray-900 hover:bg-gray-700 text-white transition duration-200 rounded-md px-4 py-2 uppercase text-lg">
            {{ trans('messages.reset-filters',[],session('locale')) }}
        </button>
    </div>

    <div class="max-w-7xl mx-auto grid gap-6 md:gap-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">

        @foreach($cars as $car)
            <a href="{{ localization()->getUrlFromRouteName(localization()->getCurrentLocale(), 'routes.our-vehicles/car', $attributes = []) }}/{{ $car->slug }}">
                <div class="car {{$car->brand->slug}}" data-price="{{ str_replace('.','',$car->price) }}" data-date="{{ $car->created_at->format('Ymd') }}">
                    @if ($image = $car->getMedia('photos')->first())
                    <img src="{{ $image->getUrl('thumb') }}" class="rounded-2xl" />
                    @else
                    <img src="{{ asset('img/placeholder.png') }}" class="rounded-2xl" />
                    @endif
                    <div style="min-height: 90px;">
                        <h3>{{ $car->title }}</h3>
                        <p class="car-price">&euro; {{ $car->price }}</p>
                    </div>
                </div>
            </a>
        @endforeach

    </div>
</div>

resources/views/livewire/cars-index.blade.php
<section class="bg-gray-100 px-4 md:px-8 py-12 md:py-20 border border-gray-200">
        
    <div class="max-w-7xl mx-auto grid gap-6 md:gap-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
    @foreach($cars->get() as $car)
        
        <a href="{{ localization()->getUrlFromRouteName(session('locale'), 'routes.our-vehicles/car', $attributes = []) }}/{{ $car->slug }}">

            <div class="rounded-2xl overflow-hidden bg-white shadow">
                <div x-data 
                    x-init="() => {
                                var glide = new Glide($el, {
                                  type: 'carousel',
                                  gap: 0,
                                });
                                glide.mount()
                            }"
                    class="glide"
                >
                    <div class="glide__track" data-glide-el="track">
                        <ul class="glide__slides">
                            @foreach($car->getMedia('photos')->take(5) as $media)
                            <li class="glide__slide">
                                <img src="{{ $media->getUrl('thumb') }}">
                            </li>
                            @endforeach
                        </ul>
                    </div>

                    <div class="absolute top-1/2 flex justify-between -mt-6 opacity-60 p-2 w-full glide__arrows" data-glide-el="controls">
                        <button class="glide__arrow glide__arrow--left" data-glide-dir="<">
                            <svg class="w-10 h-10 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm.707-10.293a1 1 0 00-1.414-1.414l-3 3a1 1 0 000 1.414l3 3a1 1 0 001.414-1.414L9.414 11H13a1 1 0 100-2H9.414l1.293-1.293z" clip-rule="evenodd"></path></svg>
                        </button>
                        <button class="glide__arrow glide__arrow--right" data-glide-dir=">">
                            <svg class="w-10 h-10 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 1.414L10.586 9H7a1 1 0 100 2h3.586l-1.293 1.293a1 1 0 101.414 1.414l3-3a1 1 0 000-1.414z" clip-rule="evenodd"></path></svg>
                        </button>
                    </div>

                   <div class="w-full absolute bottom-0 glide__bullets" data-glide-el="controls[nav]">
                        @foreach($car->getMedia('photos')->take(5) as $k => $media)
                        <button class="glide__bullet" data-glide-dir="={{ $k }}"></button>
                        @endforeach
                    </div>

                </div>

                <div class="p-4">
                    <h3 class="text-sm font-medium min-h-[50px]">{{ $car->title }}</h3>
                </div>
            </div>
        </a>

    @endforeach
    </div>
</section>

resources/views/livewire/contact-form.blade.php
<div class="pr-0 md:pr-8">
    
    @if (count($errors) > 0)
        <div class="bg-red-100 border-red-200 p-2 rounded text-red-800 mb-8">
            {{ trans('messages.all-fields') }}
        </div>
    @endif
    
    @if (Session::has('status') )
        <div class="bg-green-100 border-green-200 p-2 rounded text-green-800 mb-8">
            {{ Session::get('status') }}
        </div>
    @else

        <form wire:submit.prevent="submit">
      
            <div class="flex flex-col sm:flex-row sm:flex-wrap -mx-4 mb-4">
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4">
                    <label for="firstname" class="">{{ trans('messages.first-name') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2" id="firstname" wire:model="firstname">
                     @error('firstname') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
                
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4 mt-4 sm:mt-0">
                    <label for="lastname" class="">{{ trans('messages.last-name') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2" id="lastname" wire:model="lastname">
                     @error('lastname') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
            </div>
          
            <div class="flex flex-col sm:flex-row sm:flex-wrap -mx-4 mb-4">
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4">
                    <label for="email" class="">{{ trans('messages.e-mail') }} <sup class="text-red-500">*</sup></label>
                    <input type="email" class="bg-gray-100 border border-gray-200 rounded-md p-2" id="email" wire:model="email" value="{{ old('email') }}">
                    @error('email') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4 mt-4 sm:mt-0">
                    <label for="telephone" class="">{{ trans('messages.telephone') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2" id="telephone" wire:model="telephone" value="{{ old('telephone') }}">
                    @error('telephone') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
            </div>
          
            <div class="flex flex-col space-y-1 mb-4">
                <label for="subject" class="">{{ trans('messages.subject') }} <sup class="text-red-500">*</sup></label>
                <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2" id="subject" wire:model="subject">
                @error('subject') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div class="flex flex-col space-y-1 mb-4">
                <label for="message" class="">{{ trans('messages.message') }} <sup class="text-red-500">*</sup></label>
                <textarea class="bg-gray-100 border border-gray-200 rounded-md p-2" id="message" wire:model="message" rows="8"></textarea>
                @error(' mb-8') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div class="flex justify-end">       
                <button type="submit" class="bg-gray-700 hover:bg-gray-900 text-white transition duration-200 rounded-md px-4 py-2 uppercase text-lg">
                    {{ trans('messages.send') }}
                </button>
            </div>
        </form>

    @endif

</div>

resources/views/livewire/sell-form.blade.php
<div class="pr-0 md:pr-8">
    
    @if (count($errors) > 0)
        <div class="bg-red-100 border-red-200 p-2 rounded text-red-800 mb-8">
            {{ trans('messages.all-fields') }}
        </div>
    @endif
    
    @if (Session::has('status') )
        <div class="bg-green-100 border-green-200 p-2 rounded text-green-800 mb-8">
            {{ Session::get('status') }}
        </div>
    @else

        <form wire:submit.prevent="submit" enctype="multipart/form-data">
      
            <div class="flex flex-col sm:flex-row sm:flex-wrap -mx-4 mb-4">
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4">
                    <label for="firstname" class="">{{ trans('messages.first-name') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900" id="firstname" wire:model="firstname">
                     @error('firstname') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
                
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4 mt-4 sm:mt-0">
                    <label for="lastname" class="">{{ trans('messages.last-name') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900" id="lastname" wire:model="lastname">
                     @error('lastname') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
            </div>
          
            <div class="flex flex-col sm:flex-row sm:flex-wrap -mx-4 mb-4">
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4">
                    <label for="email" class="">{{ trans('messages.e-mail') }} <sup class="text-red-500">*</sup></label>
                    <input type="email" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900" id="email" wire:model="email" value="{{ old('email') }}">
                    @error('email') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
                <div class="w-full sm:w-1/2 flex flex-col space-y-1 px-4 mt-4 sm:mt-0">
                    <label for="telephone" class="">{{ trans('messages.telephone') }} <sup class="text-red-500">*</sup></label>
                    <input type="text" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900" id="telephone" wire:model="telephone" value="{{ old('telephone') }}">
                    @error('telephone') <span class="text-red-500">{{ $message }}</span> @enderror
                </div>
            </div>
          
            <div class="flex flex-col space-y-1 mb-4">
              <label for="brand" class="">{{ trans('messages.brand') }} <sup class="text-red-500">*</sup></label>
              <select id="brand" wire:model="brand" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900">
                    <option value=''>{{ trans('messages.make-a-choice') }}</option>
                    @foreach (App\Models\Brand::all() as $brand)
                      <option value="{{ $brand->name }}">{{ $brand->name }}</option>
                    @endforeach
              </select>
              @error('brand') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div class="flex flex-col space-y-1 mb-4">
                <label for="description" class="">{{ trans('messages.description') }} <sup class="text-red-500">*</sup></label>
                <textarea id="description" wire:model="description" rows="8" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900"></textarea>
                @error(' mb-8') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div class="flex flex-col space-y-1 mb-4">
                <label for="website" class="">{{ trans('messages.website') }}</label>
                <input type="text" id="website" wire:model="website" placeholder="http://" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900">
                @error('website') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div>
                <label for="file" class="">{{ trans('messages.file') }}</label>
                <div class="mt-1 flex items-center">
                  <input type="file" id="file" wire:model="file" class="bg-gray-100 border border-gray-200 rounded-md p-2 focus:outline-none focus:ring-gray-900 focus:border-gray-900">
                </div>
                @error('file') <span class="text-red-500">{{ $message }}</span> @enderror
            </div>

            <div class="flex justify-end">       
                <button type="submit" class="bg-gray-700 hover:bg-gray-900 text-white transition duration-200 rounded-md px-4 py-2 uppercase text-lg">
                    {{ trans('messages.send') }}
                </button>
            </div>
        </form>

    @endif

</div>